[package]
name = "tix-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tix-io = { version = "0.1.0", path = "../tix-io" }
tix-cli = { version = "0.1.0", path = "../tix-cli" }
serde_json = "1.0.151"
ratatui = "0.30.2"
crossterm = "0.29.0"

[[bin]]
name = "tix-tui"
path = "src/main.rs"
